### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by ModernGamingWorld** [juh9870/MoreMountedStorages#3]
**Describe the bug**
![2021-11-20_18 49 07](https://user-images.githubusercontent.com/75923060/142745144-464738a6-b566-45af-984a-31067ed12339.png)
[crash-2021-11-20_18.48.50-fml.txt](https://github.com/juh9870/MoreMountedStorages/files/7575587/crash-2021-11-20_18.48.50-fml.txt)

**To Reproduce**

**Additional context**
- Mod version: 1.1.0
- Forge version: 36.2.16
- Create version: 0.3.2f
- Ender Storage version:

**Comment by Elrol** [comment]
Modern brought it to my attention that there was a bug that you had to fix when using my mod, I was curious as to what the cause was and if it was something that my mod was causing

**Comment by juh9870** [comment]
@Elrol It was caused by the fact that industrial agriculture registered Rarities in `industrialagriculture:tier_x` format, and this combined by the fact that I registered black holes by iterating over Rarities, building ResourceLocation and checking if such tile entity exists, lead to the crash when my mod tried to create ResourceLocation with entry id that contained `:` symbol, leading to an unhandled exception.

**Comment by Elrol** [comment]
Ahh I see. That makes sense.
I am glad that it wasn't a more severe issue.
Thanks for explainimg that. :)
